//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liskong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IdCliente { get; set; }
        public string NumeroDeIdentidad { get; set; }
        public string NombreCompleto { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public int Telefono { get; set; }
        public string Correo { get; set; }
    }
}
