//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liskong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int IdReporte { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> Estado { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public string Detalles { get; set; }
        public string Resolucion { get; set; }
        public int FK_IdDepartamento { get; set; }
        public int FK_IdCliente { get; set; }
        public int FK_Empleado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
